server:
  port: 9412
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
spring:
  application:
    name: service-miya
  zipkin: #指定zipkin server的地址
    base-url: http://localhost:9411