server:
  port: 8761
spring:
  application:
    name: eureka-server #spring 应用名

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:       #设置与Eureka Server交互的地址，查询服务和注册服务都需要依赖这个地址
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
#    serviceUrl:  #设置与Eureka Server交互的地址，查询服务和注册服务都需要依赖这个地址。
#     默认是http://localhost:8761/eureka ；多个地址可使用 , 分隔。
#      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/